### ISSUE TITLE
v14 Tracking

### ISSUE THREAD

**Issue by ghostdevv** [ghostdevv/jellycommands#131]
Going to use this issue to track support for discord.js v14. I have only just got back from Holiday today so haven't been able to look at this up until today. I am unsure how difficult the task is going to be but we have already done updates to discord API v10 (f570a09fd348f79fca11c43004884b955ce279b4) so that should help a lot

# Todo
- [x] Update to Discord.js v14
- [x] Fix lack of string support on command options
- [x] Fix ApplicationCommandOption type 
- [x] Update create-jellycommands (code and deps)
- [x] Migration Guide
- [x] Update options section on docs

**Comment by ghostdevv** [comment]
This has just landed in `1.0.0-next.32`, I made a small migration guide here: <https://jellycommands.dev/guide/migrate/djs14.html>

Let me know if there are any issues/feedback here on [issues](https://github.com/ghostdevv/jellycommands/issues/new/choose) or in the [discord](https://discord.gg/2Vd4wAjJnm)
